name: car_app1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  get_it : ^7.6.0
  dropdown_textfield : ^1.0.8
  maps_toolkit: ^2.0.1
  dio: ^5.1.2
  shared_preferences: ^2.0.13
  location: ^4.4.0
  network_info_plus: ^4.0.1
  animated_splash_screen: ^1.3.0
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  table_calendar: ^3.0.9
  carousel_slider: ^4.2.1


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  retrofit_generator:
  flutter_native_splash:
  flutter_launcher_icons: ^0.9.2
  pretty_dio_logger: ^1.2.0-beta-1

flutter:
  uses-material-design: true

  fonts:
   - family: Poppins-Light
     fonts:
       - asset: assets/fonts/Poppins-Light.ttf
   - family: Poppins-Medium
     fonts:
       - asset: assets/fonts/Poppins-Medium.ttf    
   - family: Poppins-Regular
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf   
   - family: Poppins-SemiBold
     fonts:
       - asset: assets/fonts/Poppins-SemiBold.ttf

  assets:
   - assets/images/
   - assets/icons/
